### PR TITLE
Update odbc-sys to 0.8.2

### PR DESCRIPTION
**Pull request by Koka**
Could you please release using latest odbc-sys to provide ability to use it in odbc-rs crate

### CODE REVIEW

**Comment by palfrey** [comment]
I'm also interested in getting this merged. Anyone know what needs to be done to get this one in?

**Comment by pacman82** [comment]
Hi guys, I have sadly very little time to maintain this artifact. I'd be happy to give code ownership to @Koka.

**Comment by pacman82** [comment]
To be honest, I thought I had done so already. I added @Koka as a collaborator. I'll also look into, how I can pass ownership of this crate, on crates.io

**Comment by Koka** [comment]
Thanks @pacman82, what about odbc-sys?

**Comment by pacman82** [comment]
@Koka odbc-sys has a lot less traffic and issues, I'll keep it for now.

**Comment by pacman82** [comment]
@Koka You did receive the invitation for crates.io?

**Comment by Koka** [comment]
@pacman82 Nope, only github invitation

**Pull request merged**
